### ISSUE TITLE
Vaccination certificate is generated on the frontend side

### ISSUE THREAD

**Issue by lavar3l** [PW-MiNI-IO2-2022-Group-1/grupa-o-aabs-frontend#38]
Vaccination certificate is currently generated by the frontend which is not compliant with API specification.
Refer to: https://battnik90.stoplight.io/docs/io/d50a966a4b2b4-download-vaccination-certificate

![obraz](https://user-images.githubusercontent.com/57873253/171440159-23f44f66-e4e3-49d6-8039-0775cdab725d.png)

**Comment by V1OL3TF0X** [comment]
solved in #51

**Comment by V1OL3TF0X** [comment]
solved in #51

**Comment by lavar3l** [comment]
**Verified on develop.**
