### ISSUE TITLE
Downloading report / statistics as PDF in admin dashboard

### ISSUE THREAD

**Issue by lavar3l** [PW-MiNI-IO2-2022-Group-1/grupa-o-aabs-frontend#50]
Refer to: https://battnik90.stoplight.io/docs/io/90431eef447d6-download-vaccinations-report

**Comment by V1OL3TF0X** [comment]
fixed by #52

**Comment by V1OL3TF0X** [comment]
fixed in #51 and #52

**Comment by lavar3l** [comment]
**Verified - it's working.**
