### ISSUE TITLE
Patient vaccination list not visible

### ISSUE THREAD

**Issue by lavar3l** [PW-MiNI-IO2-2022-Group-1/grupa-o-aabs-frontend#53]
In the branch of PR #52, patient view is not showing any visits.

<img width="1506" alt="obraz" src="https://user-images.githubusercontent.com/57873253/171926807-408e06db-6a96-49ce-b8b7-f2ca44a3977d.png">

This bug prevents from verifying issue #38.

**Comment by V1OL3TF0X** [comment]
see #35 to verify

**Comment by V1OL3TF0X** [comment]
see #35 to verify

**Comment by lavar3l** [comment]
**Verified on develop.**
